{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <test_pytest.TestDemo object at 0x0000024E003F6240>\n\n    def test_two(self):\n        print(\"start to run test_two\")\n        x = \"hello\"\n>       assert hasattr(x, \"check\")\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'check')\n\ntest_pytest.py:20: AssertionError"}, "attachments": [{"name": "stdout", "source": "187e3e8d-53a6-4f25-9c10-2896a55a2930-attachment.txt", "type": "text/plain"}], "start": 1627228118049, "stop": 1627228118050, "uuid": "89baa657-1197-4abf-8cb6-1ffa38c9ae72", "historyId": "f6c8f0f6f2197f60aa9819d3caed3da8", "testCaseId": "2165935ad23331b0d15b24c1a5fce8e8", "fullName": "test_pytest.TestDemo#test_two", "labels": [{"name": "suite", "value": "test_pytest"}, {"name": "subSuite", "value": "TestDemo"}, {"name": "host", "value": "LAPTOP-CKTC9IDM"}, {"name": "thread", "value": "16832-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest"}]}